language: python
sudo: required

python:
  - '3.7'

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud activate-service-account --key-file service-account.json
  - gcloud config set project utopian-button-227405
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials cluster-2
  - npm i -g firebase firebase-tools@7.6.1
  - firebase setup:emulators:firestore
  - firebase emulators:start --only firestore &

env:
  global:
    - FIRESTORE_EMULATOR_HOST=localhost:8080
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

install:
  - pip install -e .

before_script:
  - python endpoint_server.py &

script:
  - pytest

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master