language: python
sudo: required

python:
  - '3.7'

before_install:
  - npm i -g firebase firebase-tools@7.6.1
  - firebase setup:emulators:firestore
  - firebase emulators:start --only firestore &

install:
  - pip install -e .

# before_script:
#   - python endpoint_server.py &

# script:
#   - pytest

before_deploy:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project $PROJECT_ID
  - gcloud config set compute/zone $CLUSTER_ZONE
  - gcloud container clusters get-credentials $CLUSTER_NAME

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

env:
  global:
    - FIRESTORE_EMULATOR_HOST=localhost:8080
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PROJECT_ID=utopian-button-227405
    - CLUSTER_ZONE=us-central1-c
    - CLUSTER_NAME=cluster-2