# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

name: quran.endpoints.utopian-button-227405.cloud.goog

#
# Http Transcoding.
#
# HTTP rules define translation from HTTP/REST/JSON to gRPC. With these rules
# HTTP/REST/JSON clients will be able to call the Quran service.
#

http:
  rules:
  #
  # Audio Service transcoding
  #
  - selector: quran.AudioSvc.CreateAudio
    post: '/v1/audio'
    body: '*'

  - selector: quran.AudioSvc.FindAudioById
    get: '/v1/audio/{id}'

  - selector: quran.AudioSvc.FindAudioByAyahId
    get: '/v1/audio/ayah/{id}'

  - selector: quran.AudioSvc.FindAudioByEditionId
    get: '/v1/audio/edition/{id}'

  - selector: quran.AudioSvc.FindArabicAudio
    get: '/v1/audio/arabic'

  - selector: quran.AudioSvc.FindTranslationAudio
    get: '/v1/audio/translation'

  #
  # Ayah Service transcoding
  #
  - selector: quran.AyahSvc.CreateAyah
    post: '/v1/ayah'
    body: '*'

  - selector: quran.AyahSvc.FindAyahById
    get: '/v1/ayah/{id}'

  - selector: quran.AyahSvc.FindAyahBySurahId
    get: '/v1/ayah/surah/{id}'

  - selector: quran.AyahSvc.FindAyahByNumber
    get: '/v1/ayah/number/{number}'

  - selector: quran.AyahSvc.FindAyahByNumberInSurah
    get: '/v1/ayah/number_in_surah/{number}'

  - selector: quran.AyahSvc.FindAyahByJuz
    get: '/v1/ayah/juz/{number}'

  - selector: quran.AyahSvc.FindAyahByManzil
    get: '/v1/ayah/manzil/{number}'

  - selector: quran.AyahSvc.FindAyahByRuku
    get: '/v1/ayah/ruku/{number}'

  - selector: quran.AyahSvc.FindAyahByHizbQuarter
    get: '/v1/ayah/hizb_quarter/{number}'

  - selector: quran.AyahSvc.FindAyahBySajda
    get: '/v1/ayah/sajda/{sajda}'

  #
  # Edition Service transcoding
  #
  - selector: quran.EditionSvc.CreateEdition
    post: /v1/edition
    body: '*'

  - selector: quran.EditionSvc.GetAll
    get: '/v1/edition'

  - selector: quran.EditionSvc.FindEditionById
    get: '/v1/edition/{id}'

  - selector: quran.EditionSvc.FindEditionByLanguage
    get: '/v1/edition/language/{name}'

  - selector: quran.EditionSvc.FindEditionByName
    get: '/v1/edition/name/{name}'

  - selector: quran.EditionSvc.FindEditionByEnglishName
    get: '/v1/edition/english_name/{name}'

  - selector: quran.EditionSvc.FindEditionByType
    get: '/v1/edition/type/{name}'

  - selector: quran.EditionSvc.FindEditionByFormat
    get: '/v1/edition/format/{name}'

  #
  # Image Service transcoding
  #
  - selector: quran.ImageSvc.CreateImage
    post: '/v1/image'
    body: '*'

  - selector: quran.ImageSvc.FindImageByAyahId
    get: '/v1/image/ayah/{id}'

  #
  # Surah Service transcoding
  #
  - selector: quran.SurahSvc.CreateSurah
    post: '/v1/surah'
    body: '*'

  - selector: quran.SurahSvc.GetAll
    get: '/v1/surah'

  - selector: quran.SurahSvc.FindSurahById
    get: '/v1/surah/{id}'

  - selector: quran.SurahSvc.FindSurahByNumber
    get: '/v1/surah/number/{number}'

  - selector: quran.SurahSvc.FindSurahByName
    get: '/v1/surah/name/{name}'

  - selector: quran.SurahSvc.FindSurahByEnglishName
    get: '/v1/surah/english_name/{name}'

  - selector: quran.SurahSvc.FindSurahByRevelationType
    get: '/v1/surah/type/{revelation_type}'

  #
  # Translation Service transcoding
  #
  - selector: quran.TranslationSvc.CreateTranslation
    post: '/v1/translation'
    body: '*'

  - selector: quran.TranslationSvc.FindTranslationById
    get: '/v1/translation/{id}'

  - selector: quran.TranslationSvc.FindTranslationByAyahId
    get: '/v1/translation/ayah/{id}'

  - selector: quran.TranslationSvc.FindTranslationByEditionId
    get: '/v1/translation/edition/{id}'

  - selector: quran.TranslationSvc.FilterTranslation
    get: '/v1/translation/filter'
