# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='audio.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61udio.proto\x12\x05quran\x1a\x0cshared.proto\x1a\x0c\x65ntity.proto\"-\n\tAudioList\x12 \n\naudio_list\x18\x01 \x03(\x0b\x32\x0c.quran.Audio2\xda\x02\n\x08\x41udioSvc\x12+\n\x0b\x43reateAudio\x12\x0c.quran.Audio\x1a\x0c.quran.Audio\"\x00\x12\x31\n\rFindAudioById\x12\x10.quran.IDRequest\x1a\x0c.quran.Audio\"\x00\x12\x39\n\x11\x46indAudioByAyahId\x12\x10.quran.IDRequest\x1a\x10.quran.AudioList\"\x00\x12<\n\x14\x46indAudioByEditionId\x12\x10.quran.IDRequest\x1a\x10.quran.AudioList\"\x00\x12\x37\n\x0f\x46indArabicAudio\x12\x14.quran.FilterRequest\x1a\x0c.quran.Audio\"\x00\x12<\n\x14\x46indTranslationAudio\x12\x14.quran.FilterRequest\x1a\x0c.quran.Audio\"\x00\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])




_AUDIOLIST = _descriptor.Descriptor(
  name='AudioList',
  full_name='quran.AudioList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_list', full_name='quran.AudioList.audio_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=95,
)

_AUDIOLIST.fields_by_name['audio_list'].message_type = entity__pb2._AUDIO
DESCRIPTOR.message_types_by_name['AudioList'] = _AUDIOLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioList = _reflection.GeneratedProtocolMessageType('AudioList', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOLIST,
  '__module__' : 'audio_pb2'
  # @@protoc_insertion_point(class_scope:quran.AudioList)
  })
_sym_db.RegisterMessage(AudioList)



_AUDIOSVC = _descriptor.ServiceDescriptor(
  name='AudioSvc',
  full_name='quran.AudioSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=98,
  serialized_end=444,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateAudio',
    full_name='quran.AudioSvc.CreateAudio',
    index=0,
    containing_service=None,
    input_type=entity__pb2._AUDIO,
    output_type=entity__pb2._AUDIO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAudioById',
    full_name='quran.AudioSvc.FindAudioById',
    index=1,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=entity__pb2._AUDIO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAudioByAyahId',
    full_name='quran.AudioSvc.FindAudioByAyahId',
    index=2,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_AUDIOLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAudioByEditionId',
    full_name='quran.AudioSvc.FindAudioByEditionId',
    index=3,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_AUDIOLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindArabicAudio',
    full_name='quran.AudioSvc.FindArabicAudio',
    index=4,
    containing_service=None,
    input_type=shared__pb2._FILTERREQUEST,
    output_type=entity__pb2._AUDIO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTranslationAudio',
    full_name='quran.AudioSvc.FindTranslationAudio',
    index=5,
    containing_service=None,
    input_type=shared__pb2._FILTERREQUEST,
    output_type=entity__pb2._AUDIO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUDIOSVC)

DESCRIPTOR.services_by_name['AudioSvc'] = _AUDIOSVC

# @@protoc_insertion_point(module_scope)
