# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ayah.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quran.endpoints.grpc.entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ayah.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nayah.proto\x12\x05quran\x1a\x0c\x65ntity.proto\"H\n\x0cPartsRequest\x12\x12\n\nedition_id\x18\x01 \x01(\t\x12$\n\nayah_parts\x18\x02 \x03(\x0e\x32\x10.quran.AyahParts\"D\n\rAyahIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\nayah_parts\x18\x02 \x01(\x0b\x32\x13.quran.PartsRequest\"L\n\x11\x41yahNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\'\n\nayah_parts\x18\x02 \x01(\x0b\x32\x13.quran.PartsRequest\"J\n\x10\x41yahSajdaRequest\x12\r\n\x05sajda\x18\x01 \x01(\x08\x12\'\n\nayah_parts\x18\x02 \x01(\x0b\x32\x13.quran.PartsRequest\"2\n\x08\x41yahList\x12&\n\x0b\x61yah_entity\x18\x01 \x03(\x0b\x32\x11.quran.AyahEntity*h\n\tAyahParts\x12\x0f\n\x0bTRANSLATION\x10\x00\x12\t\n\x05SURAH\x10\x01\x12\x0b\n\x07\x45\x44ITION\x10\x02\x12\x10\n\x0c\x41RABIC_AUDIO\x10\x03\x12\x15\n\x11TRANSLATION_AUDIO\x10\x04\x12\t\n\x05IMAGE\x10\x05\x32\x85\x05\n\x04\x41yah\x12\x34\n\nCreateAyah\x12\x11.quran.AyahEntity\x1a\x11.quran.AyahEntity\"\x00\x12\x39\n\x0c\x46indAyahById\x12\x14.quran.AyahIdRequest\x1a\x11.quran.AyahEntity\"\x00\x12<\n\x11\x46indAyahBySurahId\x12\x14.quran.AyahIdRequest\x1a\x0f.quran.AyahList\"\x00\x12\x41\n\x10\x46indAyahByNumber\x12\x18.quran.AyahNumberRequest\x1a\x11.quran.AyahEntity\"\x00\x12H\n\x17\x46indAyahByNumberInSurah\x12\x18.quran.AyahNumberRequest\x1a\x11.quran.AyahEntity\"\x00\x12<\n\rFindAyahByJuz\x12\x18.quran.AyahNumberRequest\x1a\x0f.quran.AyahList\"\x00\x12?\n\x10\x46indAyahByManzil\x12\x18.quran.AyahNumberRequest\x1a\x0f.quran.AyahList\"\x00\x12=\n\x0e\x46indAyahByRuku\x12\x18.quran.AyahNumberRequest\x1a\x0f.quran.AyahList\"\x00\x12\x44\n\x15\x46indAyahByHizbQuarter\x12\x18.quran.AyahNumberRequest\x1a\x0f.quran.AyahList\"\x00\x12=\n\x0f\x46indAyahBySajda\x12\x17.quran.AyahSajdaRequest\x1a\x0f.quran.AyahList\"\x00\x62\x06proto3')
  ,
  dependencies=[entity__pb2.DESCRIPTOR,])

_AYAHPARTS = _descriptor.EnumDescriptor(
  name='AyahParts',
  full_name='quran.AyahParts',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSLATION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SURAH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EDITION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARABIC_AUDIO', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSLATION_AUDIO', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=385,
  serialized_end=489,
)
_sym_db.RegisterEnumDescriptor(_AYAHPARTS)

AyahParts = enum_type_wrapper.EnumTypeWrapper(_AYAHPARTS)
TRANSLATION = 0
SURAH = 1
EDITION = 2
ARABIC_AUDIO = 3
TRANSLATION_AUDIO = 4
IMAGE = 5



_PARTSREQUEST = _descriptor.Descriptor(
  name='PartsRequest',
  full_name='quran.PartsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edition_id', full_name='quran.PartsRequest.edition_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_parts', full_name='quran.PartsRequest.ayah_parts', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=107,
)


_AYAHIDREQUEST = _descriptor.Descriptor(
  name='AyahIdRequest',
  full_name='quran.AyahIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='quran.AyahIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_parts', full_name='quran.AyahIdRequest.ayah_parts', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=177,
)


_AYAHNUMBERREQUEST = _descriptor.Descriptor(
  name='AyahNumberRequest',
  full_name='quran.AyahNumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='quran.AyahNumberRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_parts', full_name='quran.AyahNumberRequest.ayah_parts', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=255,
)


_AYAHSAJDAREQUEST = _descriptor.Descriptor(
  name='AyahSajdaRequest',
  full_name='quran.AyahSajdaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sajda', full_name='quran.AyahSajdaRequest.sajda', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_parts', full_name='quran.AyahSajdaRequest.ayah_parts', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=331,
)


_AYAHLIST = _descriptor.Descriptor(
  name='AyahList',
  full_name='quran.AyahList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ayah_entity', full_name='quran.AyahList.ayah_entity', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=383,
)

_PARTSREQUEST.fields_by_name['ayah_parts'].enum_type = _AYAHPARTS
_AYAHIDREQUEST.fields_by_name['ayah_parts'].message_type = _PARTSREQUEST
_AYAHNUMBERREQUEST.fields_by_name['ayah_parts'].message_type = _PARTSREQUEST
_AYAHSAJDAREQUEST.fields_by_name['ayah_parts'].message_type = _PARTSREQUEST
_AYAHLIST.fields_by_name['ayah_entity'].message_type = entity__pb2._AYAHENTITY
DESCRIPTOR.message_types_by_name['PartsRequest'] = _PARTSREQUEST
DESCRIPTOR.message_types_by_name['AyahIdRequest'] = _AYAHIDREQUEST
DESCRIPTOR.message_types_by_name['AyahNumberRequest'] = _AYAHNUMBERREQUEST
DESCRIPTOR.message_types_by_name['AyahSajdaRequest'] = _AYAHSAJDAREQUEST
DESCRIPTOR.message_types_by_name['AyahList'] = _AYAHLIST
DESCRIPTOR.enum_types_by_name['AyahParts'] = _AYAHPARTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PartsRequest = _reflection.GeneratedProtocolMessageType('PartsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARTSREQUEST,
  '__module__' : 'ayah_pb2'
  # @@protoc_insertion_point(class_scope:quran.PartsRequest)
  })
_sym_db.RegisterMessage(PartsRequest)

AyahIdRequest = _reflection.GeneratedProtocolMessageType('AyahIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _AYAHIDREQUEST,
  '__module__' : 'ayah_pb2'
  # @@protoc_insertion_point(class_scope:quran.AyahIdRequest)
  })
_sym_db.RegisterMessage(AyahIdRequest)

AyahNumberRequest = _reflection.GeneratedProtocolMessageType('AyahNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _AYAHNUMBERREQUEST,
  '__module__' : 'ayah_pb2'
  # @@protoc_insertion_point(class_scope:quran.AyahNumberRequest)
  })
_sym_db.RegisterMessage(AyahNumberRequest)

AyahSajdaRequest = _reflection.GeneratedProtocolMessageType('AyahSajdaRequest', (_message.Message,), {
  'DESCRIPTOR' : _AYAHSAJDAREQUEST,
  '__module__' : 'ayah_pb2'
  # @@protoc_insertion_point(class_scope:quran.AyahSajdaRequest)
  })
_sym_db.RegisterMessage(AyahSajdaRequest)

AyahList = _reflection.GeneratedProtocolMessageType('AyahList', (_message.Message,), {
  'DESCRIPTOR' : _AYAHLIST,
  '__module__' : 'ayah_pb2'
  # @@protoc_insertion_point(class_scope:quran.AyahList)
  })
_sym_db.RegisterMessage(AyahList)



_AYAH = _descriptor.ServiceDescriptor(
  name='Ayah',
  full_name='quran.Ayah',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=492,
  serialized_end=1137,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateAyah',
    full_name='quran.Ayah.CreateAyah',
    index=0,
    containing_service=None,
    input_type=entity__pb2._AYAHENTITY,
    output_type=entity__pb2._AYAHENTITY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahById',
    full_name='quran.Ayah.FindAyahById',
    index=1,
    containing_service=None,
    input_type=_AYAHIDREQUEST,
    output_type=entity__pb2._AYAHENTITY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahBySurahId',
    full_name='quran.Ayah.FindAyahBySurahId',
    index=2,
    containing_service=None,
    input_type=_AYAHIDREQUEST,
    output_type=_AYAHLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahByNumber',
    full_name='quran.Ayah.FindAyahByNumber',
    index=3,
    containing_service=None,
    input_type=_AYAHNUMBERREQUEST,
    output_type=entity__pb2._AYAHENTITY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahByNumberInSurah',
    full_name='quran.Ayah.FindAyahByNumberInSurah',
    index=4,
    containing_service=None,
    input_type=_AYAHNUMBERREQUEST,
    output_type=entity__pb2._AYAHENTITY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahByJuz',
    full_name='quran.Ayah.FindAyahByJuz',
    index=5,
    containing_service=None,
    input_type=_AYAHNUMBERREQUEST,
    output_type=_AYAHLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahByManzil',
    full_name='quran.Ayah.FindAyahByManzil',
    index=6,
    containing_service=None,
    input_type=_AYAHNUMBERREQUEST,
    output_type=_AYAHLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahByRuku',
    full_name='quran.Ayah.FindAyahByRuku',
    index=7,
    containing_service=None,
    input_type=_AYAHNUMBERREQUEST,
    output_type=_AYAHLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahByHizbQuarter',
    full_name='quran.Ayah.FindAyahByHizbQuarter',
    index=8,
    containing_service=None,
    input_type=_AYAHNUMBERREQUEST,
    output_type=_AYAHLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAyahBySajda',
    full_name='quran.Ayah.FindAyahBySajda',
    index=9,
    containing_service=None,
    input_type=_AYAHSAJDAREQUEST,
    output_type=_AYAHLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AYAH)

DESCRIPTOR.services_by_name['Ayah'] = _AYAH

# @@protoc_insertion_point(module_scope)
