# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='edition.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\redition.proto\x12\x05quran\x1a\x0cshared.proto\x1a\x0c\x65ntity.proto\"3\n\x0b\x45\x64itionList\x12$\n\x0c\x65\x64ition_list\x18\x01 \x03(\x0b\x32\x0e.quran.Edition2\xf3\x03\n\nEditionSvc\x12\x31\n\rCreateEdition\x12\x0e.quran.Edition\x1a\x0e.quran.Edition\"\x00\x12\x33\n\x06GetAll\x12\x13.quran.EmptyMessage\x1a\x12.quran.EditionList\"\x00\x12\x35\n\x0f\x46indEditionById\x12\x10.quran.IDRequest\x1a\x0e.quran.Edition\"\x00\x12\x41\n\x15\x46indEditionByLanguage\x12\x12.quran.NameRequest\x1a\x12.quran.EditionList\"\x00\x12=\n\x11\x46indEditionByName\x12\x12.quran.NameRequest\x1a\x12.quran.EditionList\"\x00\x12\x44\n\x18\x46indEditionByEnglishName\x12\x12.quran.NameRequest\x1a\x12.quran.EditionList\"\x00\x12=\n\x11\x46indEditionByType\x12\x12.quran.NameRequest\x1a\x12.quran.EditionList\"\x00\x12?\n\x13\x46indEditionByFormat\x12\x12.quran.NameRequest\x1a\x12.quran.EditionList\"\x00\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])




_EDITIONLIST = _descriptor.Descriptor(
  name='EditionList',
  full_name='quran.EditionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edition_list', full_name='quran.EditionList.edition_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=103,
)

_EDITIONLIST.fields_by_name['edition_list'].message_type = entity__pb2._EDITION
DESCRIPTOR.message_types_by_name['EditionList'] = _EDITIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EditionList = _reflection.GeneratedProtocolMessageType('EditionList', (_message.Message,), {
  'DESCRIPTOR' : _EDITIONLIST,
  '__module__' : 'edition_pb2'
  # @@protoc_insertion_point(class_scope:quran.EditionList)
  })
_sym_db.RegisterMessage(EditionList)



_EDITIONSVC = _descriptor.ServiceDescriptor(
  name='EditionSvc',
  full_name='quran.EditionSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=605,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateEdition',
    full_name='quran.EditionSvc.CreateEdition',
    index=0,
    containing_service=None,
    input_type=entity__pb2._EDITION,
    output_type=entity__pb2._EDITION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='quran.EditionSvc.GetAll',
    index=1,
    containing_service=None,
    input_type=shared__pb2._EMPTYMESSAGE,
    output_type=_EDITIONLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindEditionById',
    full_name='quran.EditionSvc.FindEditionById',
    index=2,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=entity__pb2._EDITION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindEditionByLanguage',
    full_name='quran.EditionSvc.FindEditionByLanguage',
    index=3,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=_EDITIONLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindEditionByName',
    full_name='quran.EditionSvc.FindEditionByName',
    index=4,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=_EDITIONLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindEditionByEnglishName',
    full_name='quran.EditionSvc.FindEditionByEnglishName',
    index=5,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=_EDITIONLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindEditionByType',
    full_name='quran.EditionSvc.FindEditionByType',
    index=6,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=_EDITIONLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindEditionByFormat',
    full_name='quran.EditionSvc.FindEditionByFormat',
    index=7,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=_EDITIONLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDITIONSVC)

DESCRIPTOR.services_by_name['EditionSvc'] = _EDITIONSVC

# @@protoc_insertion_point(module_scope)
