# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import quran.endpoints.grpc.edition_pb2 as edition__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2
import quran.endpoints.grpc.shared_pb2 as shared__pb2


class EditionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateEdition = channel.unary_unary(
        '/quran.Edition/CreateEdition',
        request_serializer=entity__pb2.EditionEntity.SerializeToString,
        response_deserializer=entity__pb2.EditionEntity.FromString,
        )
    self.GetAll = channel.unary_unary(
        '/quran.Edition/GetAll',
        request_serializer=shared__pb2.EmptyMessage.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindEditionById = channel.unary_unary(
        '/quran.Edition/FindEditionById',
        request_serializer=shared__pb2.IDRequest.SerializeToString,
        response_deserializer=entity__pb2.EditionEntity.FromString,
        )
    self.FindEditionByLanguage = channel.unary_unary(
        '/quran.Edition/FindEditionByLanguage',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindEditionByName = channel.unary_unary(
        '/quran.Edition/FindEditionByName',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindEditionByEnglishName = channel.unary_unary(
        '/quran.Edition/FindEditionByEnglishName',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindEditionByType = channel.unary_unary(
        '/quran.Edition/FindEditionByType',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindEditionByFormat = channel.unary_unary(
        '/quran.Edition/FindEditionByFormat',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )


class EditionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateEdition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindEditionById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindEditionByLanguage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindEditionByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindEditionByEnglishName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindEditionByType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindEditionByFormat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EditionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateEdition': grpc.unary_unary_rpc_method_handler(
          servicer.CreateEdition,
          request_deserializer=entity__pb2.EditionEntity.FromString,
          response_serializer=entity__pb2.EditionEntity.SerializeToString,
      ),
      'GetAll': grpc.unary_unary_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=shared__pb2.EmptyMessage.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindEditionById': grpc.unary_unary_rpc_method_handler(
          servicer.FindEditionById,
          request_deserializer=shared__pb2.IDRequest.FromString,
          response_serializer=entity__pb2.EditionEntity.SerializeToString,
      ),
      'FindEditionByLanguage': grpc.unary_unary_rpc_method_handler(
          servicer.FindEditionByLanguage,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindEditionByName': grpc.unary_unary_rpc_method_handler(
          servicer.FindEditionByName,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindEditionByEnglishName': grpc.unary_unary_rpc_method_handler(
          servicer.FindEditionByEnglishName,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindEditionByType': grpc.unary_unary_rpc_method_handler(
          servicer.FindEditionByType,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindEditionByFormat': grpc.unary_unary_rpc_method_handler(
          servicer.FindEditionByFormat,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'quran.Edition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
