# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import quran.endpoints.grpc.edition_pb2 as edition__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2
import quran.endpoints.grpc.shared_pb2 as shared__pb2


class EditionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateEdition = channel.unary_unary(
        '/quran.Edition/CreateEdition',
        request_serializer=entity__pb2.EditionEntity.SerializeToString,
        response_deserializer=entity__pb2.EditionEntity.FromString,
        )
    self.GetAll = channel.unary_unary(
        '/quran.Edition/GetAll',
        request_serializer=shared__pb2.EmptyMessage.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindById = channel.unary_unary(
        '/quran.Edition/FindById',
        request_serializer=shared__pb2.IDRequest.SerializeToString,
        response_deserializer=entity__pb2.EditionEntity.FromString,
        )
    self.FindByLanguage = channel.unary_unary(
        '/quran.Edition/FindByLanguage',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindByName = channel.unary_unary(
        '/quran.Edition/FindByName',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindByEnglishName = channel.unary_unary(
        '/quran.Edition/FindByEnglishName',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindByType = channel.unary_unary(
        '/quran.Edition/FindByType',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )
    self.FindByFormat = channel.unary_unary(
        '/quran.Edition/FindByFormat',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=edition__pb2.EditionList.FromString,
        )


class EditionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateEdition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByLanguage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByEnglishName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByFormat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EditionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateEdition': grpc.unary_unary_rpc_method_handler(
          servicer.CreateEdition,
          request_deserializer=entity__pb2.EditionEntity.FromString,
          response_serializer=entity__pb2.EditionEntity.SerializeToString,
      ),
      'GetAll': grpc.unary_unary_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=shared__pb2.EmptyMessage.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindById': grpc.unary_unary_rpc_method_handler(
          servicer.FindById,
          request_deserializer=shared__pb2.IDRequest.FromString,
          response_serializer=entity__pb2.EditionEntity.SerializeToString,
      ),
      'FindByLanguage': grpc.unary_unary_rpc_method_handler(
          servicer.FindByLanguage,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindByName': grpc.unary_unary_rpc_method_handler(
          servicer.FindByName,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindByEnglishName': grpc.unary_unary_rpc_method_handler(
          servicer.FindByEnglishName,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindByType': grpc.unary_unary_rpc_method_handler(
          servicer.FindByType,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
      'FindByFormat': grpc.unary_unary_rpc_method_handler(
          servicer.FindByFormat,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=edition__pb2.EditionList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'quran.Edition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
