# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entity.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x65ntity.proto\x12\x05quran\"-\n\x0bImageEntity\x12\x0f\n\x07\x61yah_id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\"p\n\x0b\x41udioEntity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61yah_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61yah_number\x18\x03 \x01(\x05\x12\x12\n\nedition_id\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\r\n\x05\x61udio\x18\x06 \x01(\t\"\x80\x01\n\rEditionEntity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ntranslator\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x06 \x01(\t\x12\x11\n\tdirection\x18\x07 \x01(\t\"g\n\x11TranslationEntity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61yah_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61yah_number\x18\x03 \x01(\x05\x12\x12\n\nedition_id\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\"\xa1\x01\n\x0bSurahEntity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x65nglish_name\x18\x04 \x01(\t\x12 \n\x18\x65nglish_name_translation\x18\x05 \x01(\t\x12\x17\n\x0fnumber_of_ayahs\x18\x06 \x01(\x05\x12\x17\n\x0frevelation_type\x18\x07 \x01(\t\"\xb3\x01\n\nAyahEntity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08surah_id\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\x05\x12\x17\n\x0fnumber_in_surah\x18\x04 \x01(\x05\x12\x0b\n\x03juz\x18\x05 \x01(\x05\x12\x0e\n\x06manzil\x18\x06 \x01(\x05\x12\x0c\n\x04ruku\x18\x07 \x01(\x05\x12\x14\n\x0chizb_quarter\x18\x08 \x01(\x05\x12\r\n\x05sajda\x18\t \x01(\x08\x12\x0e\n\x06\x61rabic\x18\n \x01(\tb\x06proto3')
)




_IMAGEENTITY = _descriptor.Descriptor(
  name='ImageEntity',
  full_name='quran.ImageEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ayah_id', full_name='quran.ImageEntity.ayah_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='quran.ImageEntity.image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=68,
)


_AUDIOENTITY = _descriptor.Descriptor(
  name='AudioEntity',
  full_name='quran.AudioEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='quran.AudioEntity.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_id', full_name='quran.AudioEntity.ayah_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_number', full_name='quran.AudioEntity.ayah_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edition_id', full_name='quran.AudioEntity.edition_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='quran.AudioEntity.type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='quran.AudioEntity.audio', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=182,
)


_EDITIONENTITY = _descriptor.Descriptor(
  name='EditionEntity',
  full_name='quran.EditionEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='quran.EditionEntity.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='quran.EditionEntity.language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='quran.EditionEntity.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translator', full_name='quran.EditionEntity.translator', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='quran.EditionEntity.type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='quran.EditionEntity.format', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='quran.EditionEntity.direction', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=313,
)


_TRANSLATIONENTITY = _descriptor.Descriptor(
  name='TranslationEntity',
  full_name='quran.TranslationEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='quran.TranslationEntity.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_id', full_name='quran.TranslationEntity.ayah_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ayah_number', full_name='quran.TranslationEntity.ayah_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edition_id', full_name='quran.TranslationEntity.edition_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='quran.TranslationEntity.text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=418,
)


_SURAHENTITY = _descriptor.Descriptor(
  name='SurahEntity',
  full_name='quran.SurahEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='quran.SurahEntity.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='quran.SurahEntity.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='quran.SurahEntity.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='english_name', full_name='quran.SurahEntity.english_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='english_name_translation', full_name='quran.SurahEntity.english_name_translation', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_ayahs', full_name='quran.SurahEntity.number_of_ayahs', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revelation_type', full_name='quran.SurahEntity.revelation_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=582,
)


_AYAHENTITY = _descriptor.Descriptor(
  name='AyahEntity',
  full_name='quran.AyahEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='quran.AyahEntity.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surah_id', full_name='quran.AyahEntity.surah_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='quran.AyahEntity.number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_in_surah', full_name='quran.AyahEntity.number_in_surah', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='juz', full_name='quran.AyahEntity.juz', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manzil', full_name='quran.AyahEntity.manzil', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ruku', full_name='quran.AyahEntity.ruku', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hizb_quarter', full_name='quran.AyahEntity.hizb_quarter', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sajda', full_name='quran.AyahEntity.sajda', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arabic', full_name='quran.AyahEntity.arabic', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=764,
)

DESCRIPTOR.message_types_by_name['ImageEntity'] = _IMAGEENTITY
DESCRIPTOR.message_types_by_name['AudioEntity'] = _AUDIOENTITY
DESCRIPTOR.message_types_by_name['EditionEntity'] = _EDITIONENTITY
DESCRIPTOR.message_types_by_name['TranslationEntity'] = _TRANSLATIONENTITY
DESCRIPTOR.message_types_by_name['SurahEntity'] = _SURAHENTITY
DESCRIPTOR.message_types_by_name['AyahEntity'] = _AYAHENTITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageEntity = _reflection.GeneratedProtocolMessageType('ImageEntity', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEENTITY,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:quran.ImageEntity)
  })
_sym_db.RegisterMessage(ImageEntity)

AudioEntity = _reflection.GeneratedProtocolMessageType('AudioEntity', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOENTITY,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:quran.AudioEntity)
  })
_sym_db.RegisterMessage(AudioEntity)

EditionEntity = _reflection.GeneratedProtocolMessageType('EditionEntity', (_message.Message,), {
  'DESCRIPTOR' : _EDITIONENTITY,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:quran.EditionEntity)
  })
_sym_db.RegisterMessage(EditionEntity)

TranslationEntity = _reflection.GeneratedProtocolMessageType('TranslationEntity', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATIONENTITY,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:quran.TranslationEntity)
  })
_sym_db.RegisterMessage(TranslationEntity)

SurahEntity = _reflection.GeneratedProtocolMessageType('SurahEntity', (_message.Message,), {
  'DESCRIPTOR' : _SURAHENTITY,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:quran.SurahEntity)
  })
_sym_db.RegisterMessage(SurahEntity)

AyahEntity = _reflection.GeneratedProtocolMessageType('AyahEntity', (_message.Message,), {
  'DESCRIPTOR' : _AYAHENTITY,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:quran.AyahEntity)
  })
_sym_db.RegisterMessage(AyahEntity)


# @@protoc_insertion_point(module_scope)
