# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import quran.endpoints.grpc.entity_pb2 as entity__pb2
import quran.endpoints.grpc.image_pb2 as image__pb2
import quran.endpoints.grpc.shared_pb2 as shared__pb2


class ImageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateImage = channel.unary_unary(
        '/quran.Image/CreateImage',
        request_serializer=entity__pb2.ImageEntity.SerializeToString,
        response_deserializer=image__pb2.ImageSingleResponse.FromString,
        )
    self.FindImageByAyahId = channel.unary_unary(
        '/quran.Image/FindImageByAyahId',
        request_serializer=shared__pb2.IDRequest.SerializeToString,
        response_deserializer=image__pb2.ImageSingleResponse.FromString,
        )


class ImageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindImageByAyahId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateImage': grpc.unary_unary_rpc_method_handler(
          servicer.CreateImage,
          request_deserializer=entity__pb2.ImageEntity.FromString,
          response_serializer=image__pb2.ImageSingleResponse.SerializeToString,
      ),
      'FindImageByAyahId': grpc.unary_unary_rpc_method_handler(
          servicer.FindImageByAyahId,
          request_deserializer=shared__pb2.IDRequest.FromString,
          response_serializer=image__pb2.ImageSingleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'quran.Image', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
