# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cshared.proto\x12\x05quran\"\x0e\n\x0c\x45mptyMessage\"\x17\n\tIDRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1b\n\x0bNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\rFilterRequest\x12#\n\x06\x66ilter\x18\x01 \x03(\x0b\x32\x13.quran.StringFilter\"+\n\x0cStringFilter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')
)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='quran.EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=37,
)


_IDREQUEST = _descriptor.Descriptor(
  name='IDRequest',
  full_name='quran.IDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='quran.IDRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=62,
)


_NUMBERREQUEST = _descriptor.Descriptor(
  name='NumberRequest',
  full_name='quran.NumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='quran.NumberRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=95,
)


_NAMEREQUEST = _descriptor.Descriptor(
  name='NameRequest',
  full_name='quran.NameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='quran.NameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=124,
)


_FILTERREQUEST = _descriptor.Descriptor(
  name='FilterRequest',
  full_name='quran.FilterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='quran.FilterRequest.filter', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=178,
)


_STRINGFILTER = _descriptor.Descriptor(
  name='StringFilter',
  full_name='quran.StringFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='quran.StringFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='quran.StringFilter.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=223,
)

_FILTERREQUEST.fields_by_name['filter'].message_type = _STRINGFILTER
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['IDRequest'] = _IDREQUEST
DESCRIPTOR.message_types_by_name['NumberRequest'] = _NUMBERREQUEST
DESCRIPTOR.message_types_by_name['NameRequest'] = _NAMEREQUEST
DESCRIPTOR.message_types_by_name['FilterRequest'] = _FILTERREQUEST
DESCRIPTOR.message_types_by_name['StringFilter'] = _STRINGFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:quran.EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

IDRequest = _reflection.GeneratedProtocolMessageType('IDRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDREQUEST,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:quran.IDRequest)
  })
_sym_db.RegisterMessage(IDRequest)

NumberRequest = _reflection.GeneratedProtocolMessageType('NumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERREQUEST,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:quran.NumberRequest)
  })
_sym_db.RegisterMessage(NumberRequest)

NameRequest = _reflection.GeneratedProtocolMessageType('NameRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAMEREQUEST,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:quran.NameRequest)
  })
_sym_db.RegisterMessage(NameRequest)

FilterRequest = _reflection.GeneratedProtocolMessageType('FilterRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILTERREQUEST,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:quran.FilterRequest)
  })
_sym_db.RegisterMessage(FilterRequest)

StringFilter = _reflection.GeneratedProtocolMessageType('StringFilter', (_message.Message,), {
  'DESCRIPTOR' : _STRINGFILTER,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:quran.StringFilter)
  })
_sym_db.RegisterMessage(StringFilter)


# @@protoc_insertion_point(module_scope)
