# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import quran.endpoints.grpc.entity_pb2 as entity__pb2
import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.surah_pb2 as surah__pb2


class SurahSvcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSurah = channel.unary_unary(
        '/quran.SurahSvc/CreateSurah',
        request_serializer=entity__pb2.Surah.SerializeToString,
        response_deserializer=entity__pb2.Surah.FromString,
        )
    self.GetAll = channel.unary_unary(
        '/quran.SurahSvc/GetAll',
        request_serializer=shared__pb2.EmptyMessage.SerializeToString,
        response_deserializer=surah__pb2.SurahList.FromString,
        )
    self.FindSurahById = channel.unary_unary(
        '/quran.SurahSvc/FindSurahById',
        request_serializer=shared__pb2.IDRequest.SerializeToString,
        response_deserializer=entity__pb2.Surah.FromString,
        )
    self.FindSurahByNumber = channel.unary_unary(
        '/quran.SurahSvc/FindSurahByNumber',
        request_serializer=shared__pb2.NumberRequest.SerializeToString,
        response_deserializer=entity__pb2.Surah.FromString,
        )
    self.FindSurahByName = channel.unary_unary(
        '/quran.SurahSvc/FindSurahByName',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=entity__pb2.Surah.FromString,
        )
    self.FindSurahByEnglishName = channel.unary_unary(
        '/quran.SurahSvc/FindSurahByEnglishName',
        request_serializer=shared__pb2.NameRequest.SerializeToString,
        response_deserializer=entity__pb2.Surah.FromString,
        )
    self.FindSurahByRevelationType = channel.unary_unary(
        '/quran.SurahSvc/FindSurahByRevelationType',
        request_serializer=surah__pb2.RevelationRequest.SerializeToString,
        response_deserializer=surah__pb2.SurahList.FromString,
        )


class SurahSvcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateSurah(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindSurahById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindSurahByNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindSurahByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindSurahByEnglishName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindSurahByRevelationType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SurahSvcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSurah': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSurah,
          request_deserializer=entity__pb2.Surah.FromString,
          response_serializer=entity__pb2.Surah.SerializeToString,
      ),
      'GetAll': grpc.unary_unary_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=shared__pb2.EmptyMessage.FromString,
          response_serializer=surah__pb2.SurahList.SerializeToString,
      ),
      'FindSurahById': grpc.unary_unary_rpc_method_handler(
          servicer.FindSurahById,
          request_deserializer=shared__pb2.IDRequest.FromString,
          response_serializer=entity__pb2.Surah.SerializeToString,
      ),
      'FindSurahByNumber': grpc.unary_unary_rpc_method_handler(
          servicer.FindSurahByNumber,
          request_deserializer=shared__pb2.NumberRequest.FromString,
          response_serializer=entity__pb2.Surah.SerializeToString,
      ),
      'FindSurahByName': grpc.unary_unary_rpc_method_handler(
          servicer.FindSurahByName,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=entity__pb2.Surah.SerializeToString,
      ),
      'FindSurahByEnglishName': grpc.unary_unary_rpc_method_handler(
          servicer.FindSurahByEnglishName,
          request_deserializer=shared__pb2.NameRequest.FromString,
          response_serializer=entity__pb2.Surah.SerializeToString,
      ),
      'FindSurahByRevelationType': grpc.unary_unary_rpc_method_handler(
          servicer.FindSurahByRevelationType,
          request_deserializer=surah__pb2.RevelationRequest.FromString,
          response_serializer=surah__pb2.SurahList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'quran.SurahSvc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
