# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: surah.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='surah.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bsurah.proto\x12\x05quran\x1a\x0cshared.proto\x1a\x0c\x65ntity.proto\"-\n\tSurahList\x12 \n\nsurah_list\x18\x01 \x03(\x0b\x32\x0c.quran.Surah\",\n\x11RevelationRequest\x12\x17\n\x0frevelation_type\x18\x01 \x01(\t2\x98\x03\n\x08SurahSvc\x12+\n\x0b\x43reateSurah\x12\x0c.quran.Surah\x1a\x0c.quran.Surah\"\x00\x12\x31\n\x06GetAll\x12\x13.quran.EmptyMessage\x1a\x10.quran.SurahList\"\x00\x12\x31\n\rFindSurahById\x12\x10.quran.IDRequest\x1a\x0c.quran.Surah\"\x00\x12\x39\n\x11\x46indSurahByNumber\x12\x14.quran.NumberRequest\x1a\x0c.quran.Surah\"\x00\x12\x35\n\x0f\x46indSurahByName\x12\x12.quran.NameRequest\x1a\x0c.quran.Surah\"\x00\x12<\n\x16\x46indSurahByEnglishName\x12\x12.quran.NameRequest\x1a\x0c.quran.Surah\"\x00\x12I\n\x19\x46indSurahByRevelationType\x12\x18.quran.RevelationRequest\x1a\x10.quran.SurahList\"\x00\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])




_SURAHLIST = _descriptor.Descriptor(
  name='SurahList',
  full_name='quran.SurahList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='surah_list', full_name='quran.SurahList.surah_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=95,
)


_REVELATIONREQUEST = _descriptor.Descriptor(
  name='RevelationRequest',
  full_name='quran.RevelationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='revelation_type', full_name='quran.RevelationRequest.revelation_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=141,
)

_SURAHLIST.fields_by_name['surah_list'].message_type = entity__pb2._SURAH
DESCRIPTOR.message_types_by_name['SurahList'] = _SURAHLIST
DESCRIPTOR.message_types_by_name['RevelationRequest'] = _REVELATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SurahList = _reflection.GeneratedProtocolMessageType('SurahList', (_message.Message,), {
  'DESCRIPTOR' : _SURAHLIST,
  '__module__' : 'surah_pb2'
  # @@protoc_insertion_point(class_scope:quran.SurahList)
  })
_sym_db.RegisterMessage(SurahList)

RevelationRequest = _reflection.GeneratedProtocolMessageType('RevelationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVELATIONREQUEST,
  '__module__' : 'surah_pb2'
  # @@protoc_insertion_point(class_scope:quran.RevelationRequest)
  })
_sym_db.RegisterMessage(RevelationRequest)



_SURAHSVC = _descriptor.ServiceDescriptor(
  name='SurahSvc',
  full_name='quran.SurahSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=144,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSurah',
    full_name='quran.SurahSvc.CreateSurah',
    index=0,
    containing_service=None,
    input_type=entity__pb2._SURAH,
    output_type=entity__pb2._SURAH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='quran.SurahSvc.GetAll',
    index=1,
    containing_service=None,
    input_type=shared__pb2._EMPTYMESSAGE,
    output_type=_SURAHLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahById',
    full_name='quran.SurahSvc.FindSurahById',
    index=2,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=entity__pb2._SURAH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByNumber',
    full_name='quran.SurahSvc.FindSurahByNumber',
    index=3,
    containing_service=None,
    input_type=shared__pb2._NUMBERREQUEST,
    output_type=entity__pb2._SURAH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByName',
    full_name='quran.SurahSvc.FindSurahByName',
    index=4,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=entity__pb2._SURAH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByEnglishName',
    full_name='quran.SurahSvc.FindSurahByEnglishName',
    index=5,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=entity__pb2._SURAH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByRevelationType',
    full_name='quran.SurahSvc.FindSurahByRevelationType',
    index=6,
    containing_service=None,
    input_type=_REVELATIONREQUEST,
    output_type=_SURAHLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SURAHSVC)

DESCRIPTOR.services_by_name['SurahSvc'] = _SURAHSVC

# @@protoc_insertion_point(module_scope)
