# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: surah.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='surah.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bsurah.proto\x12\x05quran\x1a\x0cshared.proto\x1a\x0c\x65ntity.proto\",\n\x11RevelationRequest\x12\x17\n\x0frevelation_type\x18\x01 \x01(\t\"f\n\x13SurahSingleResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12 \n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x12.quran.SurahEntity\x12\x0f\n\x07message\x18\x04 \x01(\t\"T\n\x12SurahMultiResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12 \n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x12.quran.SurahEntity2\xf3\x03\n\x05Surah\x12?\n\x0b\x43reateSurah\x12\x12.quran.SurahEntity\x1a\x1a.quran.SurahSingleResponse\"\x00\x12:\n\x06GetAll\x12\x13.quran.EmptyMessage\x1a\x19.quran.SurahMultiResponse\"\x00\x12?\n\rFindSurahById\x12\x10.quran.IDRequest\x1a\x1a.quran.SurahSingleResponse\"\x00\x12G\n\x11\x46indSurahByNumber\x12\x14.quran.NumberRequest\x1a\x1a.quran.SurahSingleResponse\"\x00\x12\x43\n\x0f\x46indSurahByName\x12\x12.quran.NameRequest\x1a\x1a.quran.SurahSingleResponse\"\x00\x12J\n\x16\x46indSurahByEnglishName\x12\x12.quran.NameRequest\x1a\x1a.quran.SurahSingleResponse\"\x00\x12R\n\x19\x46indSurahByRevelationType\x12\x18.quran.RevelationRequest\x1a\x19.quran.SurahMultiResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])




_REVELATIONREQUEST = _descriptor.Descriptor(
  name='RevelationRequest',
  full_name='quran.RevelationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='revelation_type', full_name='quran.RevelationRequest.revelation_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=94,
)


_SURAHSINGLERESPONSE = _descriptor.Descriptor(
  name='SurahSingleResponse',
  full_name='quran.SurahSingleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='quran.SurahSingleResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='quran.SurahSingleResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='quran.SurahSingleResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='quran.SurahSingleResponse.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=198,
)


_SURAHMULTIRESPONSE = _descriptor.Descriptor(
  name='SurahMultiResponse',
  full_name='quran.SurahMultiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='quran.SurahMultiResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='quran.SurahMultiResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='quran.SurahMultiResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=284,
)

_SURAHSINGLERESPONSE.fields_by_name['data'].message_type = entity__pb2._SURAHENTITY
_SURAHMULTIRESPONSE.fields_by_name['data'].message_type = entity__pb2._SURAHENTITY
DESCRIPTOR.message_types_by_name['RevelationRequest'] = _REVELATIONREQUEST
DESCRIPTOR.message_types_by_name['SurahSingleResponse'] = _SURAHSINGLERESPONSE
DESCRIPTOR.message_types_by_name['SurahMultiResponse'] = _SURAHMULTIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RevelationRequest = _reflection.GeneratedProtocolMessageType('RevelationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVELATIONREQUEST,
  '__module__' : 'surah_pb2'
  # @@protoc_insertion_point(class_scope:quran.RevelationRequest)
  })
_sym_db.RegisterMessage(RevelationRequest)

SurahSingleResponse = _reflection.GeneratedProtocolMessageType('SurahSingleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SURAHSINGLERESPONSE,
  '__module__' : 'surah_pb2'
  # @@protoc_insertion_point(class_scope:quran.SurahSingleResponse)
  })
_sym_db.RegisterMessage(SurahSingleResponse)

SurahMultiResponse = _reflection.GeneratedProtocolMessageType('SurahMultiResponse', (_message.Message,), {
  'DESCRIPTOR' : _SURAHMULTIRESPONSE,
  '__module__' : 'surah_pb2'
  # @@protoc_insertion_point(class_scope:quran.SurahMultiResponse)
  })
_sym_db.RegisterMessage(SurahMultiResponse)



_SURAH = _descriptor.ServiceDescriptor(
  name='Surah',
  full_name='quran.Surah',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=287,
  serialized_end=786,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSurah',
    full_name='quran.Surah.CreateSurah',
    index=0,
    containing_service=None,
    input_type=entity__pb2._SURAHENTITY,
    output_type=_SURAHSINGLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='quran.Surah.GetAll',
    index=1,
    containing_service=None,
    input_type=shared__pb2._EMPTYMESSAGE,
    output_type=_SURAHMULTIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahById',
    full_name='quran.Surah.FindSurahById',
    index=2,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_SURAHSINGLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByNumber',
    full_name='quran.Surah.FindSurahByNumber',
    index=3,
    containing_service=None,
    input_type=shared__pb2._NUMBERREQUEST,
    output_type=_SURAHSINGLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByName',
    full_name='quran.Surah.FindSurahByName',
    index=4,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=_SURAHSINGLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByEnglishName',
    full_name='quran.Surah.FindSurahByEnglishName',
    index=5,
    containing_service=None,
    input_type=shared__pb2._NAMEREQUEST,
    output_type=_SURAHSINGLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSurahByRevelationType',
    full_name='quran.Surah.FindSurahByRevelationType',
    index=6,
    containing_service=None,
    input_type=_REVELATIONREQUEST,
    output_type=_SURAHMULTIRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SURAH)

DESCRIPTOR.services_by_name['Surah'] = _SURAH

# @@protoc_insertion_point(module_scope)
