# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import quran.endpoints.grpc.entity_pb2 as entity__pb2
import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.translation_pb2 as translation__pb2


class TranslationSvcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTranslation = channel.unary_unary(
        '/quran.TranslationSvc/CreateTranslation',
        request_serializer=entity__pb2.Translation.SerializeToString,
        response_deserializer=entity__pb2.Translation.FromString,
        )
    self.FindTranslationById = channel.unary_unary(
        '/quran.TranslationSvc/FindTranslationById',
        request_serializer=shared__pb2.IDRequest.SerializeToString,
        response_deserializer=entity__pb2.Translation.FromString,
        )
    self.FindTranslationByAyahId = channel.unary_unary(
        '/quran.TranslationSvc/FindTranslationByAyahId',
        request_serializer=shared__pb2.IDRequest.SerializeToString,
        response_deserializer=translation__pb2.TranslationList.FromString,
        )
    self.FindTranslationByEditionId = channel.unary_unary(
        '/quran.TranslationSvc/FindTranslationByEditionId',
        request_serializer=shared__pb2.IDRequest.SerializeToString,
        response_deserializer=translation__pb2.TranslationList.FromString,
        )
    self.FilterTranslation = channel.unary_unary(
        '/quran.TranslationSvc/FilterTranslation',
        request_serializer=shared__pb2.FilterRequest.SerializeToString,
        response_deserializer=entity__pb2.Translation.FromString,
        )


class TranslationSvcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateTranslation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindTranslationById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindTranslationByAyahId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindTranslationByEditionId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FilterTranslation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TranslationSvcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTranslation': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTranslation,
          request_deserializer=entity__pb2.Translation.FromString,
          response_serializer=entity__pb2.Translation.SerializeToString,
      ),
      'FindTranslationById': grpc.unary_unary_rpc_method_handler(
          servicer.FindTranslationById,
          request_deserializer=shared__pb2.IDRequest.FromString,
          response_serializer=entity__pb2.Translation.SerializeToString,
      ),
      'FindTranslationByAyahId': grpc.unary_unary_rpc_method_handler(
          servicer.FindTranslationByAyahId,
          request_deserializer=shared__pb2.IDRequest.FromString,
          response_serializer=translation__pb2.TranslationList.SerializeToString,
      ),
      'FindTranslationByEditionId': grpc.unary_unary_rpc_method_handler(
          servicer.FindTranslationByEditionId,
          request_deserializer=shared__pb2.IDRequest.FromString,
          response_serializer=translation__pb2.TranslationList.SerializeToString,
      ),
      'FilterTranslation': grpc.unary_unary_rpc_method_handler(
          servicer.FilterTranslation,
          request_deserializer=shared__pb2.FilterRequest.FromString,
          response_serializer=entity__pb2.Translation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'quran.TranslationSvc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
