# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='translation.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11translation.proto\x12\x05quran\x1a\x0cshared.proto\x1a\x0c\x65ntity.proto\"G\n\x0fTranslationList\x12\x34\n\x12translation_entity\x18\x01 \x03(\x0b\x32\x18.quran.TranslationEntity2\xf5\x02\n\x0bTranslation\x12I\n\x11\x43reateTranslation\x12\x18.quran.TranslationEntity\x1a\x18.quran.TranslationEntity\"\x00\x12\x43\n\x13\x46indTranslationById\x12\x10.quran.IDRequest\x1a\x18.quran.TranslationEntity\"\x00\x12\x45\n\x17\x46indTranslationByAyahId\x12\x10.quran.IDRequest\x1a\x16.quran.TranslationList\"\x00\x12H\n\x1a\x46indTranslationByEditionId\x12\x10.quran.IDRequest\x1a\x16.quran.TranslationList\"\x00\x12\x45\n\x11\x46ilterTranslation\x12\x14.quran.FilterRequest\x1a\x18.quran.TranslationEntity\"\x00\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])




_TRANSLATIONLIST = _descriptor.Descriptor(
  name='TranslationList',
  full_name='quran.TranslationList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation_entity', full_name='quran.TranslationList.translation_entity', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=127,
)

_TRANSLATIONLIST.fields_by_name['translation_entity'].message_type = entity__pb2._TRANSLATIONENTITY
DESCRIPTOR.message_types_by_name['TranslationList'] = _TRANSLATIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TranslationList = _reflection.GeneratedProtocolMessageType('TranslationList', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATIONLIST,
  '__module__' : 'translation_pb2'
  # @@protoc_insertion_point(class_scope:quran.TranslationList)
  })
_sym_db.RegisterMessage(TranslationList)



_TRANSLATION = _descriptor.ServiceDescriptor(
  name='Translation',
  full_name='quran.Translation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=503,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTranslation',
    full_name='quran.Translation.CreateTranslation',
    index=0,
    containing_service=None,
    input_type=entity__pb2._TRANSLATIONENTITY,
    output_type=entity__pb2._TRANSLATIONENTITY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTranslationById',
    full_name='quran.Translation.FindTranslationById',
    index=1,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=entity__pb2._TRANSLATIONENTITY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTranslationByAyahId',
    full_name='quran.Translation.FindTranslationByAyahId',
    index=2,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_TRANSLATIONLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTranslationByEditionId',
    full_name='quran.Translation.FindTranslationByEditionId',
    index=3,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_TRANSLATIONLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FilterTranslation',
    full_name='quran.Translation.FilterTranslation',
    index=4,
    containing_service=None,
    input_type=shared__pb2._FILTERREQUEST,
    output_type=entity__pb2._TRANSLATIONENTITY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSLATION)

DESCRIPTOR.services_by_name['Translation'] = _TRANSLATION

# @@protoc_insertion_point(module_scope)
