# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quran.endpoints.grpc.shared_pb2 as shared__pb2
import quran.endpoints.grpc.entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='translation.proto',
  package='quran',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11translation.proto\x12\x05quran\x1a\x0cshared.proto\x1a\x0c\x65ntity.proto\"e\n\x19TranslationSingleResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12*\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1c.quran.TranslationSingleData\"c\n\x18TranslationMultiResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12)\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1b.quran.TranslationMultiData\"a\n\x15TranslationSingleData\x12-\n\x0btranslation\x18\x01 \x01(\x0b\x32\x18.quran.TranslationEntity\x12\x19\n\x11number_of_results\x18\x02 \x01(\x05\"p\n\x14TranslationMultiData\x12-\n\x0btranslation\x18\x01 \x03(\x0b\x32\x18.quran.TranslationEntity\x12\x19\n\x11number_of_results\x18\x02 \x01(\x05\x12\x0e\n\x06\x63ursor\x18\x03 \x01(\t2\x9f\x03\n\x0bTranslation\x12Q\n\x11\x43reateTranslation\x12\x18.quran.TranslationEntity\x1a .quran.TranslationSingleResponse\"\x00\x12K\n\x13\x46indTranslationById\x12\x10.quran.IDRequest\x1a .quran.TranslationSingleResponse\"\x00\x12N\n\x17\x46indTranslationByAyahId\x12\x10.quran.IDRequest\x1a\x1f.quran.TranslationMultiResponse\"\x00\x12Q\n\x1a\x46indTranslationByEditionId\x12\x10.quran.IDRequest\x1a\x1f.quran.TranslationMultiResponse\"\x00\x12M\n\x11\x46ilterTranslation\x12\x14.quran.FilterRequest\x1a .quran.TranslationSingleResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])




_TRANSLATIONSINGLERESPONSE = _descriptor.Descriptor(
  name='TranslationSingleResponse',
  full_name='quran.TranslationSingleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='quran.TranslationSingleResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='quran.TranslationSingleResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='quran.TranslationSingleResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=157,
)


_TRANSLATIONMULTIRESPONSE = _descriptor.Descriptor(
  name='TranslationMultiResponse',
  full_name='quran.TranslationMultiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='quran.TranslationMultiResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='quran.TranslationMultiResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='quran.TranslationMultiResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=258,
)


_TRANSLATIONSINGLEDATA = _descriptor.Descriptor(
  name='TranslationSingleData',
  full_name='quran.TranslationSingleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='quran.TranslationSingleData.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_results', full_name='quran.TranslationSingleData.number_of_results', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=357,
)


_TRANSLATIONMULTIDATA = _descriptor.Descriptor(
  name='TranslationMultiData',
  full_name='quran.TranslationMultiData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='quran.TranslationMultiData.translation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_results', full_name='quran.TranslationMultiData.number_of_results', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='quran.TranslationMultiData.cursor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=471,
)

_TRANSLATIONSINGLERESPONSE.fields_by_name['data'].message_type = _TRANSLATIONSINGLEDATA
_TRANSLATIONMULTIRESPONSE.fields_by_name['data'].message_type = _TRANSLATIONMULTIDATA
_TRANSLATIONSINGLEDATA.fields_by_name['translation'].message_type = entity__pb2._TRANSLATIONENTITY
_TRANSLATIONMULTIDATA.fields_by_name['translation'].message_type = entity__pb2._TRANSLATIONENTITY
DESCRIPTOR.message_types_by_name['TranslationSingleResponse'] = _TRANSLATIONSINGLERESPONSE
DESCRIPTOR.message_types_by_name['TranslationMultiResponse'] = _TRANSLATIONMULTIRESPONSE
DESCRIPTOR.message_types_by_name['TranslationSingleData'] = _TRANSLATIONSINGLEDATA
DESCRIPTOR.message_types_by_name['TranslationMultiData'] = _TRANSLATIONMULTIDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TranslationSingleResponse = _reflection.GeneratedProtocolMessageType('TranslationSingleResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATIONSINGLERESPONSE,
  '__module__' : 'translation_pb2'
  # @@protoc_insertion_point(class_scope:quran.TranslationSingleResponse)
  })
_sym_db.RegisterMessage(TranslationSingleResponse)

TranslationMultiResponse = _reflection.GeneratedProtocolMessageType('TranslationMultiResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATIONMULTIRESPONSE,
  '__module__' : 'translation_pb2'
  # @@protoc_insertion_point(class_scope:quran.TranslationMultiResponse)
  })
_sym_db.RegisterMessage(TranslationMultiResponse)

TranslationSingleData = _reflection.GeneratedProtocolMessageType('TranslationSingleData', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATIONSINGLEDATA,
  '__module__' : 'translation_pb2'
  # @@protoc_insertion_point(class_scope:quran.TranslationSingleData)
  })
_sym_db.RegisterMessage(TranslationSingleData)

TranslationMultiData = _reflection.GeneratedProtocolMessageType('TranslationMultiData', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATIONMULTIDATA,
  '__module__' : 'translation_pb2'
  # @@protoc_insertion_point(class_scope:quran.TranslationMultiData)
  })
_sym_db.RegisterMessage(TranslationMultiData)



_TRANSLATION = _descriptor.ServiceDescriptor(
  name='Translation',
  full_name='quran.Translation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=474,
  serialized_end=889,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTranslation',
    full_name='quran.Translation.CreateTranslation',
    index=0,
    containing_service=None,
    input_type=entity__pb2._TRANSLATIONENTITY,
    output_type=_TRANSLATIONSINGLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTranslationById',
    full_name='quran.Translation.FindTranslationById',
    index=1,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_TRANSLATIONSINGLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTranslationByAyahId',
    full_name='quran.Translation.FindTranslationByAyahId',
    index=2,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_TRANSLATIONMULTIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindTranslationByEditionId',
    full_name='quran.Translation.FindTranslationByEditionId',
    index=3,
    containing_service=None,
    input_type=shared__pb2._IDREQUEST,
    output_type=_TRANSLATIONMULTIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FilterTranslation',
    full_name='quran.Translation.FilterTranslation',
    index=4,
    containing_service=None,
    input_type=shared__pb2._FILTERREQUEST,
    output_type=_TRANSLATIONSINGLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSLATION)

DESCRIPTOR.services_by_name['Translation'] = _TRANSLATION

# @@protoc_insertion_point(module_scope)
